### ISSUE TITLE
Bad output

### ISSUE THREAD

**Issue by jcreinhold** [Jfortin1/RAVEL#8] opened 2018-05-29 17:24 UTC
I am trying to use RAVEL on a set of deformably co-registered T1-w MR images, but the algorithm is not working as expected. An example result is shown in the picture below:

![ravel_result](https://user-images.githubusercontent.com/5241441/40673009-56c10fac-6325-11e8-9887-79c8203a2caa.png)

For more information, the control (CSF) mask I am using seems to make sense and I am providing the input in the way the documentation seems to suggest using the RAVEL package. Note that I am using the WhiteStripe option in this example, but I have used the package without WhiteStripe and gotten similar results.

Does the input require any additional processing that I am not doing to produce a good result? I can provide more detail as needed.

Thanks for the help

**Comment by abdhigithub** [comment] 2018-05-31 17:21
You've included the intersection of all CSF masks in the co-registered space as the control mask right? as well as the brain masks in the co-registered space? Also are you using the option writeToDisk? In my experience I obtain the matrix of normalized intensities and create the image myself. I don't see right away why it would not be working. Any more details maybe helpful.

**Comment by jcreinhold** [comment] 2018-06-01 01:59
I am using the intersection of CSF masks in the co-registered space. I also use the brain mask of the template image (i.e., the image that all the images are registered to) as input. I was using the writeToDisk option.

I tried the script without the writeToDisk option and saved the normalized images myself and the output appears reasonable. 

The previous problem stemmed from the writeToDisk option which saved the images as uint8. I'll let someone else close this issue since this appears to be a problem with the code. 

For information on my build: I'm using R version 3.4.1, and up-to-date versions of all the dependencies (as of last week). I installed the package and its dependencies through neuroconductor.

**Comment by abdhigithub** [comment] 2018-06-01 04:15
Glad that worked out.  I'll try to pass on the bug fix.  Thanks :)

**Comment by jcreinhold** [comment] 2018-06-01 16:45
Thanks again for the help. One more question (I can open another issue if desired):

Whenever I use RAVEL, I receive the warning:

**Using all slices of the image as slices not defined! Use stripped = TRUE if using skull-stripped images.**

However, when I set stripped = TRUE, then I get the following error: 

**Error in model.frame.default(formula = y ~ X - 1, drop.unused.levels = TRUE) :
  invalid type (list) for variable 'X'**

Even though the images are already skull-stripped. I believe this is actually a WhiteStripe problem, but I'm not sure.

To be clear, the output appears ok with the warning, but I just want to make sure I'm using the function as expected. Thanks again!

**Comment by abdhigithub** [comment] 2018-06-01 17:08
Ummm yeah you're right. Odd thing is, this method demands brain masks so in a way it's odd that it would even ask for stripped==TRUE. Either way the error shouldn't have occurred because of the change in that option. Whitestripe is not affected too much by that option, it is just a way to improve the computation time. Thanks for highlighting these issues.

**Comment by tetrille** [comment] 2019-01-04 16:56
Hello, I am experiencing the same issue as @jcreinhold. My R version is 3.5.2, and I'm working with T1-weighted images coregistered to the JHI-MNI-ss template, masked with the template brainmask and segmented as described in README.md. See example output from normalizeRAVEL below.

![image](https://user-images.githubusercontent.com/46378476/50697893-da219d00-1043-11e9-9dc4-035424bc61eb.png)

When I call normalizeRAVEL with WhiteStripe == FALSE the artifacts disappear, and running normalizeWS reproduces the artifacts, so the problem looks like it might be caused by WhiteStripe. Do you have any suggestions how to get around this problem?

In RAVEL/normalizeRAVEL.R I noticed that returnMatrix == TRUE returns V, but V.norm appears to be the normalised values as output by ravel_correction(V, Z). I might be missing something, but does calling normalizeRAVEL with returnMatrix == TRUE return the full RAVEL-adjusted intensities?

Thank you for the help!

**Comment by muschellij2** [comment] 2019-01-07 19:02
Can you provide your example image to show an MCVE: https://stackoverflow.com/help/mcve?

**Comment by tetrille** [comment] 2019-02-21 11:55
Hello again,

Has anyone had a chance to look at this issue?

**Comment by Jfortin1** [comment] 2019-02-21 17:47
@tetrille Yes, sorry for the slow response; I am still working on solving the issue.

**Comment by Jfortin1** [comment] 2019-02-21 23:33
@tetrille I have now fixed the problem and bumped the version up. The problem was with the function used to write the normalized images to the disk (writeNIfTI); it did not recognize the data type and was not handling negative values properly. This has been fixed, and writeNIfTI() has been replaced with writeni(). Thank you for bringing this up and sharing your code.

**Closed by Jfortin1** 2019-02-21 23:33 UTC

**Comment by tetrille** [comment] 2019-02-22 14:14
That is brilliant! It works now and output seems reasonable. Thanks.
