### ISSUE TITLE
Funky "normalized" T1w's

### ISSUE THREAD

**Issue by jimcost** [Jfortin1/RAVEL#10] opened 2019-04-05 00:18 UTC
Hello human(s),

I am attempting to execute `normalizeRAVEL` on a patient set of 10. The command I execute is `rav <- normalizeRAVEL(infiles, out.files = NULL, brain.mask = bmask, control.mask = cmask, WhiteStripe_Type = "T1", writeToDisk = TRUE, stripped = TRUE)`

The `cmask` variable was created using `cmask <- maskIntersect(csf_masks, output.file="intersection_mask.nii.gz", prob=1.0)`

An image of `cmask`:

![image](https://user-images.githubusercontent.com/6710629/55596409-96ebce80-5705-11e9-852b-a776765f9031.png)

The underlying T1w is MNI-registered, and while it contains a skull (used to evaluate CSF mask) the T1w's in the normalization command above are skull-stripped.

An image of a single normalization brain:

![image](https://user-images.githubusercontent.com/6710629/55596458-cef31180-5705-11e9-8cdd-c2b53691fafc.png)

Any ideas? Across the 10 patients the intensities ranges are - 

(0.000000 3728.828125) | (0.000000 5149.502441) | (0.000000 2619.226074) | (0.000000 2390.880127) | (0.000000 4490.105469) | (0.000000 1955.639648) | (0.000000 4625.776855)  | (0.000000 5375.570801) | (0.000000 4419.894043)

**Comment by jimcost** [comment] 2019-04-05 00:20
One last item: excluding `cmask` and executing `normalizeWS` does not fair better:

![image](https://user-images.githubusercontent.com/6710629/55596547-580a4880-5706-11e9-8017-312ee2852bf3.png)

**Comment by jimcost** [comment] 2019-04-05 17:17
One last item: excluding `cmask` and executing `normalizeWS` does not fair better:

![Uploading image.png…]()

**Comment by jimcost** [comment] 2019-04-11 18:50
Thinking the issue may have to do with the differences in ranges, I attempted to execute RAVEL on both -z-scored and fuzzy c-means normalized MRIs. Unfortunately, this did not improve the situation:

![image](https://user-images.githubusercontent.com/6710629/55983410-51c12280-5c58-11e9-8c47-f6e87ccdda6b.png)

**Comment by muschellij2** [comment] 2019-04-12 14:07
Please provide some example data and exact code you are running so that we
can diagnose or provide a MCVE: https://stackoverflow.com/help/mcve
John

**Comment by jimcost** [comment] 2019-04-12 19:15
The exact code was given:

`cmask <- maskIntersect(csf_masks, output.file="intersection_mask.nii.gz", prob=1.0)`
`normalizeRAVEL(infiles, out.files = NULL, brain.mask = bmask, control.mask = cmask, WhiteStripe_Type = "T1", writeToDisk = TRUE, stripped = TRUE)`

The MRI are MNI-registered, and `bmask` is a binarized version of FSL's MNI atlas "MNI152lin_T1_1mm_brain.nii.gz"

What do you have in mind for example data? Please be more specific.

**Comment by Jfortin1** [comment] 2019-04-12 19:31
It seems to me that high intensities on the normalized images were not written correctly to disk, which was an issue that we fixed in the latest version of RAVEL. @jimcost may I ask which version of RAVEL are you using?

**Comment by jimcost** [comment] 2019-04-15 21:37
Hi @Jfortin1 - I am using RAVEL version 1.1.1 on a Ubuntu 18.04 LTS computer.

Hi @muschellij2 -The exact code is

`cmask <- maskIntersect(csf_masks, output.file="intersection_mask.nii.gz", prob=1.0)`
`normalizeRAVEL(infiles, out.files = NULL, brain.mask = bmask, control.mask = cmask, WhiteStripe_Type = "T1", writeToDisk = TRUE, stripped = TRUE)`

I attached a compressed folder containing the csf masks (used to create `cmask` using `maskIntersect`) and `infiles` for 3 patients, along with `bmask` (a binarized mask created using FSL's MNI library). I also included an intersection mask from the 10 patient-set as well, in case there is some complaint due to the voxels on the outer rim of the brain. Regardless of mask used or number of patients included in the normalization, the written images appear the same as those shown above.

Also, while we are talking - one other hurdle I ran into - the `out.files` field does not save to the intended location. An example of out.files input:

`outfiles <- c("/mnt/Rsrch4/ImgData/TissueClass2018/mriIntentsityNorm/T1/TC00_RAVEL.nii.gz",
"/mnt/Rsrch4/ImgData/TissueClass2018/mriIntentsityNorm/T1/TC01_RAVEL.nii.gz", "/mnt/Rsrch4/ImgData/TissueClass2018/mriIntentsityNorm/T1/TC04_RAVEL.nii.gz") `

This variable appears to be ignored and the saved images are saved to the `input.files` location.

[ravel_exp_data.zip](https://github.com/Jfortin1/RAVEL/files/3082155/ravel_exp_data.zip)

**Comment by jimcost** [comment] 2019-04-15 22:50
I installed RAVEL version 1.2.1, here is an example output:
![image](https://user-images.githubusercontent.com/6710629/56170135-a2f54d00-5f9d-11e9-8d45-7cf2bbe12ac5.png)
The output is much improved! Does it appear reasonable from your experience?

With respect to saving images, I executed `rav <- normalizeRAVEL(infiles, out.files = outfiles, brain.mask = bmask, control.mask = cmask, WhiteStripe_Type = "T1", writeToDisk = TRUE)`
where `outfiles <- list("/mnt/Rsrch4/ImgData/TissueClass2018/mriIntentsityNorm/T1/TC00_RAVEL.nii.gz",...)` and so on. However, the files continue to save to the `input.files` directory.

**Comment by Jfortin1** [comment] 2019-04-15 23:24
Have you tried outfiles <- c("/mnt/Rsrch4/ImgData/TissueClass2018/mriIntentsityNorm/T1/TC00_RAVEL.nii.gz") as a vector instead of a list?

**Comment by jimcost** [comment] 2019-04-15 23:45
Yes, without success. Other attempts I made were (1) executing RStudio as root and (2) creating both `infiles` and `outfiles` with `c()` (for thoroughness' sake). Any other ideas?

**Comment by muschellij2** [comment] 2019-04-16 16:53
The problem is that the argument is `output.files`, not `out.files`.  
```
library(RAVEL)
setwd("~/Downloads/ravel_exp_data/")

bmask = "MNI152lin_T1_1mm_brain_mask.nii.gz"
cmask = "intersection_mask_ten.nii.gz"
infiles = c("pnt0_t12mni.nii.gz", 
            "pnt1_t12mni.nii.gz", 
            "pnt2_t12mni.nii.gz")
output.files = sapply(1:3, function(x) {
  tempfile(fileext = ".nii.gz")
})

res = normalizeRAVEL(
  infiles, 
  output.files = output.files, 
  brain.mask = bmask, control.mask = cmask, 
  WhiteStripe_Type = "T1", 
  writeToDisk = TRUE)
```

**Comment by Jfortin1** [comment] 2019-04-16 17:07
Thanks @muschellij2.

**Closed by Jfortin1** 2019-04-16 17:07 UTC

**Comment by jimcost** [comment] 2019-04-16 21:01
Ahh yes, apologies.
